
import React,{useEffect,useMemo,useState} from "react";

const t={name:"WSOP Monster Stack Final Table",stage:"Final Table",date:"2025-07-14",buyIn:"$1,500",prizePool:"$10.2M",indexedHands:184,highlights:14};
const players=[
{id:"p1",name:"Seth Davies",exploit:78,conf:"High",hands:3842,fts:17,vpip:21,pfr:17,threebet:6,style:"TAG / ICM cautious"},
{id:"p2",name:"Alex Foxen",exploit:55,conf:"Medium",hands:1620,fts:8,vpip:24,pfr:20,threebet:8,style:"Balanced aggressive"},
{id:"p3",name:"Chris Brewer",exploit:69,conf:"Medium",hands:980,fts:6,vpip:27,pfr:22,threebet:9,style:"LAG pressure"},
];
const hands=[
{id:18,tag:"Turning Point",street:"Preflop",pot:"$2.75M",spot:"20bb jam/call",yt:"1:23:51",score:92},
{id:23,tag:"ICM Overfold",street:"Flop",pot:"$1.10M",spot:"BB vs BTN",yt:"1:41:07",score:88},
{id:31,tag:"River Bluff",street:"River",pot:"$850K",spot:"Polar jam",yt:"1:58:11",score:75},
{id:36,tag:"Thin Value",street:"River",pot:"$640K",spot:"Block bet raise",yt:"2:07:04",score:69},
];
const highs=[{id:"h1",handId:18,title:"Biggest all-in collision"},{id:"h2",handId:23,title:"ICM overfold in BB vs BTN"},{id:"h3",handId:31,title:"River jam bluff sequence"}];
const ev={
p1:[{handId:23,leak:"Overfolds BB vs BTN",evidence:"68% fold vs 52% population",sample:"421 nodes",conf:"High",action:"Steal wider / pressure more"},
    {handId:31,leak:"Under-bluffs river",evidence:"18% vs 31% population",sample:"97 nodes",conf:"Medium",action:"Fold more bluff-catchers"}],
p2:[{handId:36,leak:"Thin value over-extension",evidence:"Value density too high on paired boards",sample:"48 nodes",conf:"Low",action:"Trap stronger"}],
p3:[{handId:31,leak:"Pressure-heavy river",evidence:"Overpolarizes vs capped ranges",sample:"53 nodes",conf:"Medium",action:"Induce / trap selectively"}]
};
const routes=[["search","Search"],["tournament","Tournament"],["hands","Hands"],["hand","Hand Detail"],["players","Players"],["player","Player Detail"],["highlights","Highlights"],["ai","AI Studio"],["answer","AI Answer"],["evidence","Evidence"],["report","Exploit Report"],["watchlist","Watchlist"],["notes","Notes"],["pricing","Pricing"],["settings","Settings"]];

function useHashRoute(){
  const parse=()=>{const raw=(window.location.hash||"#/search").slice(2); const [path,qs]=raw.split("?"); return {path:path||"search",params:new URLSearchParams(qs||"")};};
  const [r,setR]=useState(parse());
  useEffect(()=>{const f=()=>setR(parse()); window.addEventListener("hashchange",f); if(!window.location.hash) window.location.hash="/search"; return()=>window.removeEventListener("hashchange",f);},[]);
  const go=(path,params={})=>{const q=new URLSearchParams(params).toString(); window.location.hash=`/${path}${q?("?"+q):""}`;};
  return [r,go];
}
const Kpi=({label,value})=><div className="kpi"><span>{label}</span><strong>{value}</strong></div>;
const Card=({title,right,children})=><section className="card"><div className="cardHead"><h3>{title}</h3>{right}</div><div className="cardBody">{children}</div></section>;

export default function App(){
  const [route,go]=useHashRoute();
  const [replay,setReplay]=useState("animated");
  const [scope,setScope]=useState("tournament");
  const [saved,setSaved]=useState(["ICM pressure increased exploitability after Hand #18.","Reduce bluff-catches vs under-bluff river nodes."]);
  const handId=Number(route.params.get("hand")||18), playerId=route.params.get("player")||"p1";
  const hand=useMemo(()=>hands.find(h=>h.id===handId)||hands[0],[handId]);
  const player=useMemo(()=>players.find(p=>p.id===playerId)||players[0],[playerId]);
  const body={
    search:<Search go={go}/>, tournament:<Tournament go={go}/>, hands:<Hands go={go}/>,
    hand:<Hand go={go} hand={hand} replay={replay} setReplay={setReplay}/>,
    players:<Players go={go}/>, player:<Player go={go} player={player}/>,
    highlights:<Highlights go={go}/>, ai:<AIStudio go={go} scope={scope} setScope={setScope} hand={hand} player={player}/>,
    answer:<AIAnswer go={go} hand={hand} player={player} qid={route.params.get("qid")||"example"}/>,
    evidence:<Evidence go={go} player={player}/>, report:<Report go={go} player={player}/>,
    watchlist:<Watchlist go={go}/>, notes:<Notes go={go} saved={saved} setSaved={setSaved}/>,
    pricing:<Pricing/>, settings:<Settings/>
  }[route.path] || <Card title="Not found"><button className="btn" onClick={()=>go("search")}>Go Search</button></Card>;
  return <div className="app">
    <header className="topbar">
      <div className="brandWrap"><div className="logo">H</div><div><div className="brand">HUDR MVP Release Prototype</div><div className="sub">All links wired · Tournament-first paid-beta flow</div></div></div>
      <div className="metaPills"><span>{t.name}</span><span>{t.stage}</span><span>{t.date}</span></div>
      <div className="actions"><button className="btn ghost" onClick={()=>go("search")}>Search</button><button className="btn ghost" onClick={()=>go("tournament")}>Tournament</button><button className="btn primary" onClick={()=>go("ai")}>Ask AI</button></div>
    </header>
    <div className="shell">
      <aside className="left">
        <div className="panel"><div className="panelTitle">MVP Navigation</div>{routes.map(([id,l])=><button key={id} className={`navBtn ${route.path===id?"active":""}`} onClick={()=>go(id)}>{l}</button>)}</div>
        <div className="panel"><div className="panelTitle">Core release flow</div>
          <button className="linkRow" onClick={()=>go("search")}><span>1. Find tournament</span><strong>Start</strong></button>
          <button className="linkRow" onClick={()=>go("players")}><span>2. Inspect players</span><strong>HUD+Exploit</strong></button>
          <button className="linkRow" onClick={()=>go("ai")}><span>3. Ask AI</span><strong>Guided</strong></button>
          <button className="linkRow" onClick={()=>go("report",{player:"p1"})}><span>4. Generate report</span><strong>Prep sheet</strong></button>
        </div>
      </aside>
      <main className="main">{body}</main>
      <aside className="right">
        <div className="panel"><div className="panelTitle">Selection</div><div className="kpiGrid compact"><Kpi label="Hand" value={`#${hand.id}`}/><Kpi label="Player" value={player.name}/><Kpi label="Exploit" value={`${player.exploit}/100`}/><Kpi label="Conf" value={player.conf}/></div></div>
        <div className="panel"><div className="panelTitle">MVP readiness</div>{["Search","Hands+Players","AI prompts","Evidence chain","Replay launch","Exploit report","Notes/Watchlist","Pricing gate"].map(x=><div key={x} className="check ok">{x}</div>)}</div>
      </aside>
    </div>
    <footer className="mobileNav"><button onClick={()=>go("search")}>Search</button><button onClick={()=>go("hands")}>Hands</button><button onClick={()=>go("players")}>Players</button><button onClick={()=>go("ai")}>AI</button></footer>
  </div>;
}

function Search({go}){return <div className="stack lg"><Card title="Tournament Search" right={<span className="pill">MVP entry</span>}><div className="toolbar"><input className="input" placeholder="Search tournament / player / series..."/><button className="btn">Filter</button></div><div className="searchCard"><div className="rowTitle">{t.name}</div><div className="muted">{t.buyIn} · {t.stage} · {t.date} · {t.prizePool}</div><div className="chips"><span>FT</span><span>ICM</span><span>YouTube</span><span>AI-ready</span></div><div className="rowActions mt"><button className="btn primary" onClick={()=>go("tournament")}>Analyze Tournament</button><button className="btn" onClick={()=>go("highlights")}>Highlights</button><button className="btn ghost" onClick={()=>go("hands")}>Hands</button></div></div></Card></div>;}
function Tournament({go}){return <div className="stack lg"><Card title="Tournament Analysis Home" right={<span className="pill">Primary release screen</span>}><div className="grid two"><div className="hero"><div className="heroTitle">{t.name}</div><div className="heroSub">Analyze tournament like a pro: hands, players, AI insights, highlights, YouTube + animated replays.</div><div className="kpiGrid mt"><Kpi label="Hands Indexed" value={t.indexedHands}/><Kpi label="Players" value={9}/><Kpi label="Highlights" value={t.highlights}/><Kpi label="AI Tabs" value={4}/></div></div><div className="stack"><button className="linkRow" onClick={()=>go("hands")}><span>Hands Explorer</span><strong>Replay-linked</strong></button><button className="linkRow" onClick={()=>go("players")}><span>Players</span><strong>HUD + exploit</strong></button><button className="linkRow" onClick={()=>go("highlights")}><span>Highlights</span><strong>Fast study path</strong></button><button className="linkRow" onClick={()=>go("ai")}><span>AI Studio</span><strong>Tournament / player / hand / strategy</strong></button></div></div></Card><Card title="AI Tournament Summary"><div className="callout"><strong>Quick story</strong><p>ICM pressure increases exploitability in conservative blind defense nodes after Hand #18. Highest confidence exploit path is evidence-backed and replay-linked.</p></div><div className="rowActions mt"><button className="btn" onClick={()=>go("answer",{qid:"biggest-icm-mistakes"})}>Open AI Answer</button><button className="btn" onClick={()=>go("report",{player:"p1"})}>Generate Exploit Report</button></div></Card></div>;}
function Hands({go}){const [street,setStreet]=useState("All"); const rows=hands.filter(h=>street==="All"||h.street===street); return <div className="stack lg"><Card title="Hands Explorer" right={<span className="pill">Evidence + replay ready</span>}><div className="toolbar">{["All","Preflop","Flop","River"].map(s=><button key={s} className={`chipBtn ${street===s?"active":""}`} onClick={()=>setStreet(s)}>{s}</button>)}</div><div className="tableLike"><div className="thead"><span>Hand</span><span>Street</span><span>Spot</span><span>Impact</span><span>Actions</span></div>{rows.map(h=><div className="trow" key={h.id}><span>#{h.id} · {h.tag}</span><span>{h.street}</span><span>{h.spot}</span><span>{h.score}</span><span className="rowActions"><button className="btn" onClick={()=>go("hand",{hand:h.id})}>Detail</button><button className="btn" onClick={()=>go("answer",{qid:`hand-${h.id}`,hand:h.id})}>AI</button></span></div>)}</div></Card></div>;}
function Hand({go,hand,replay,setReplay}){return <div className="stack lg"><Card title={`Hand #${hand.id} · ${hand.tag}`} right={<button className="btn" onClick={()=>go("hands")}>Back to Hands</button>}><div className="toolbar"><div className="seg"><button className={replay==="animated"?"active":""} onClick={()=>setReplay("animated")}>Animated</button><button className={replay==="youtube"?"active yt":""} onClick={()=>setReplay("youtube")}>YouTube</button></div><button className="btn primary" onClick={()=>go("answer",{qid:`explain-hand-${hand.id}`,hand:hand.id})}>Ask AI</button></div><div className="grid two"><div className="stage"><div className="center"><div className="rowTitle">{replay==="animated"?"Animated Hand Replayer":"YouTube Replay Surface"}</div><div className="muted">{replay==="animated"?"Pot progression · street transitions":"Jump to timestamp "+hand.yt}</div></div></div><div className="stack"><div className="callout danger"><strong>AI signal</strong><p>Potential exploitable decision node based on player profile and population baseline.</p></div><div className="callout good"><strong>Counter-adjustment</strong><p>Apply confidence-weighted exploit and verify with evidence chain.</p></div><div className="kpiGrid compact"><Kpi label="Street" value={hand.street}/><Kpi label="Pot" value={hand.pot}/><Kpi label="Spot" value={hand.spot}/><Kpi label="Impact" value={hand.score}/></div><div className="rowActions"><button className="btn" onClick={()=>go("evidence",{player:"p1"})}>Evidence Chain</button><button className="btn" onClick={()=>go("report",{player:"p1"})}>Exploit Report</button></div></div></div></Card></div>;}
function Players({go}){return <div className="stack lg"><Card title="Players in Tournament" right={<span className="pill">50+ HUD stats concept</span>}><div className="playerGrid">{players.map(p=><div className="playerCard" key={p.id}><div className="rowTitle">{p.name}</div><div className="muted">{p.style} · {p.hands.toLocaleString()} hands · {p.fts} FTs · {p.conf}</div><div className="kpiGrid compact mt"><Kpi label="Exploit" value={`${p.exploit}/100`}/><Kpi label="VPIP" value={`${p.vpip}%`}/><Kpi label="PFR" value={`${p.pfr}%`}/><Kpi label="3Bet" value={`${p.threebet}%`}/></div><div className="rowActions mt"><button className="btn primary" onClick={()=>go("player",{player:p.id})}>Open</button><button className="btn" onClick={()=>go("report",{player:p.id})}>Report</button><button className="btn ghost" onClick={()=>go("answer",{qid:`player-${p.id}`,player:p.id})}>AI</button></div></div>)}</div></Card></div>;}
function Player({go,player}){const [tab,setTab]=useState("exploit"); const rows=ev[player.id]||[]; return <div className="stack lg"><Card title={player.name} right={<button className="btn primary" onClick={()=>go("report",{player:player.id})}>Open Exploit Report</button>}><div className="metaPills"><span>{player.style}</span><span>{player.hands.toLocaleString()} hands</span><span>{player.fts} FTs</span><span>{player.conf} confidence</span></div><div className="tabStrip mt">{["exploit","hud","evidence","strategy","chat"].map(t=><button key={t} className={tab===t?"tabActive":""} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==="exploit"&&<div className="stack mt">{rows.map((r,i)=><div className="callout danger" key={i}><strong>{r.leak}</strong><p>{r.evidence} · {r.sample} · {r.conf}</p><div className="exploitLine"><span>How to play vs</span>{r.action}</div><div className="rowActions mt"><button className="btn" onClick={()=>go("hand",{hand:r.handId})}>Open Hand #{r.handId}</button><button className="btn ghost" onClick={()=>go("evidence",{player:player.id})}>Evidence Chain</button></div></div>)}</div>}{tab==="hud"&&<div className="kpiGrid mt"><Kpi label="VPIP" value={`${player.vpip}%`}/><Kpi label="PFR" value={`${player.pfr}%`}/><Kpi label="3Bet" value={`${player.threebet}%`}/><Kpi label="Exploit" value={`${player.exploit}/100`}/><Kpi label="Confidence" value={player.conf}/><Kpi label="Hands" value={player.hands}/><Kpi label="FTs" value={player.fts}/><Kpi label="Freshness" value="Updated 3d ago"/></div>}{tab==="evidence"&&<div className="stack mt">{rows.map((r,i)=><button key={i} className="linkRow" onClick={()=>go("hand",{hand:r.handId})}><span>Hand #{r.handId} · {r.leak}</span><strong>{r.conf}</strong></button>)}<button className="btn" onClick={()=>go("evidence",{player:player.id})}>Open Full Evidence Chain</button></div>}{tab==="strategy"&&<div className="grid two mt"><div className="callout good"><strong>Primary exploit strategy</strong><ul><li>Attack confirmed overfold nodes</li><li>Reduce bluff catches vs under-bluff lines</li><li>Apply confidence thresholds</li></ul></div><div className="callout"><strong>Do not over-adjust when</strong><ul><li>Low sample</li><li>Out of context stack depth</li><li>Weak evidence confidence</li></ul></div></div>}{tab==="chat"&&<div className="stack mt"><div className="promptGrid">{[`How to exploit ${player.name}?`,`Top leaks with evidence`,`What changes under ICM?`,`Show supporting hands`].map(q=><button key={q} className="promptBtn" onClick={()=>go("answer",{qid:q,player:player.id})}>{q}</button>)}</div><div className="toolbar"><input className="input" placeholder={`Ask about ${player.name}...`}/><button className="btn primary" onClick={()=>go("answer",{qid:"custom-player-query",player:player.id})}>Ask</button></div></div>}</Card></div>;}
function Highlights({go}){return <div className="stack lg"><Card title="Tournament Highlights" right={<span className="pill">Fast path</span>}>{highs.map(h=><div key={h.id} className="listRow"><div><div className="rowTitle">{h.title}</div><div className="muted">Hand #{h.handId} · Replay + AI</div></div><div className="rowActions"><button className="btn" onClick={()=>go("hand",{hand:h.handId})}>Replay / Detail</button><button className="btn ghost" onClick={()=>go("answer",{qid:`highlight-${h.id}`,hand:h.handId})}>AI</button></div></div>)}</Card></div>;}
function AIStudio({go,scope,setScope,hand,player}){const prompts={tournament:["Who is most exploitable in this FT?","Show biggest ICM mistakes","What are the turning points?"],player:[`How to exploit ${player.name}?`,"Top leaks with confidence","Show evidence-backed reads"],hand:[`Explain Hand #${hand.id}`,"What is the likely mistake?","What is the counter-strategy?"],strategy:["ICM exploit checklist","BB vs BTN exploit framework","River under-bluff counterplay"]}; return <div className="stack lg"><Card title="AI Insights Studio" right={<span className="pill">Guided prompts + scope tabs</span>}><div className="tabStrip">{Object.keys(prompts).map(k=><button key={k} className={scope===k?"tabActive":""} onClick={()=>setScope(k)}>{k}</button>)}</div><div className="grid two mt"><div className="stack"><div className="callout"><strong>Use AI in MVP</strong><p>Pick a scope → ask guided question → review evidence → jump to replay/report.</p></div><div className="promptGrid">{prompts[scope].map(q=><button key={q} className="promptBtn" onClick={()=>go("answer",{qid:q,player:player.id,hand:hand.id})}>{q}</button>)}</div></div><div className="stack"><div className="callout good"><strong>Answer structure</strong><ul><li>Summary</li><li>Evidence links</li><li>Confidence</li><li>Next actions</li></ul></div><button className="linkRow" onClick={()=>go("answer",{qid:"most-exploitable-player",player:"p1",hand:23})}><span>Example answer</span><strong>Try now</strong></button><button className="linkRow" onClick={()=>go("pricing")}><span>See Pro plan gating</span><strong>$10/mo</strong></button></div></div><div className="toolbar mt"><input className="input" placeholder="Ask about tournament, player, hand, strategy..."/><button className="btn primary" onClick={()=>go("answer",{qid:"custom-query",player:player.id,hand:hand.id})}>Ask</button></div></Card></div>;}
function AIAnswer({go,hand,player,qid}){return <div className="stack lg"><Card title="AI Answer" right={<div className="rowActions"><button className="btn" onClick={()=>go("evidence",{player:player.id})}>Evidence</button><button className="btn" onClick={()=>go("report",{player:player.id})}>Save to Report</button></div>}><div className="callout"><strong>Question</strong><p>{qid}</p></div><div className="callout good"><strong>Summary</strong><p>Highest confidence edge is against {player.name} in FT blind defense and selected river under-bluff nodes. Supporting examples include Hand #{hand.id}. Use confidence-weighted exploit adjustments.</p></div><div className="grid two"><div className="panel inset"><div className="panelTitle">Evidence links</div><button className="linkRow" onClick={()=>go("evidence",{player:player.id})}><span>Open evidence chain</span><strong>{player.name}</strong></button><button className="linkRow" onClick={()=>go("hand",{hand:23})}><span>Hand #23</span><strong>ICM overfold</strong></button><button className="linkRow" onClick={()=>go("hand",{hand:31})}><span>Hand #31</span><strong>River node</strong></button></div><div className="panel inset"><div className="panelTitle">Next actions</div><button className="linkRow" onClick={()=>go("report",{player:player.id})}><span>Generate exploit report</span><strong>Prep</strong></button><button className="linkRow" onClick={()=>go("notes")}><span>Save note</span><strong>Study</strong></button><button className="linkRow" onClick={()=>go("watchlist")}><span>Add watchlist</span><strong>Track</strong></button></div></div><div className="metaPills mt"><span>Confidence: {player.conf}</span><span>Sample shown in evidence</span><span>Freshness: Updated 3d ago</span></div></Card></div>;}
function Evidence({go,player}){const rows=ev[player.id]||[]; return <div className="stack lg"><Card title={`Evidence Chain · ${player.name}`} right={<button className="btn" onClick={()=>go("player",{player:player.id})}>Back to Player</button>}>{rows.map((r,i)=><div key={i} className="evidenceRow"><div className="evIndex">{i+1}</div><div className="evBody"><div className="rowTitle">{r.leak}</div><div className="muted">{r.evidence} · {r.sample} · {r.conf}</div><div className="exploitLine"><span>Action</span>{r.action}</div><div className="rowActions mt"><button className="btn" onClick={()=>go("hand",{hand:r.handId})}>Open Hand #{r.handId}</button><button className="btn ghost" onClick={()=>go("answer",{qid:`evidence-${i+1}`,player:player.id,hand:r.handId})}>AI Explain</button></div></div></div>)}</Card></div>;}
function Report({go,player}){const rows=ev[player.id]||[]; return <div className="stack lg"><Card title={`Exploit Report · ${player.name}`} right={<div className="rowActions"><button className="btn" onClick={()=>go("pricing")}>Upgrade Gate</button><button className="btn primary">Export PDF (UI)</button></div>}><div className="kpiGrid"><Kpi label="Exploit Score" value={`${player.exploit}/100`}/><Kpi label="Confidence" value={player.conf}/><Kpi label="Hands" value={player.hands}/><Kpi label="FTs" value={player.fts}/></div><div className="grid two mt"><div className="stack"><div className="callout good"><strong>Executive Summary</strong><p>{player.name} shows actionable edge in blind defense and selected river frequency deviations. Use evidence-backed exploit lines with confidence thresholds.</p></div><div className="panel inset"><div className="panelTitle">Top leaks</div>{rows.map((r,i)=><div key={i} className="miniRow"><span>{r.leak}</span><span className="muted">{r.conf}</span></div>)}</div></div><div className="stack"><div className="panel inset"><div className="panelTitle">Evidence hands</div>{rows.map((r,i)=><button key={i} className="linkRow" onClick={()=>go("hand",{hand:r.handId})}><span>Hand #{r.handId}</span><strong>{r.leak}</strong></button>)}</div><div className="callout"><strong>Action checklist</strong><ul><li>Review evidence hands</li><li>Check confidence + sample</li><li>Save notes</li><li>Add player to watchlist</li></ul></div></div></div></Card></div>;}
function Watchlist({go}){return <div className="stack lg"><Card title="Watchlist / Opponent Prep Queue" right={<span className="pill">Retention MVP</span>}>{players.map(p=><div key={p.id} className="listRow"><div><div className="rowTitle">{p.name}</div><div className="muted">Saved from AI / report flow · Exploit {p.exploit}/100</div></div><div className="rowActions"><button className="btn" onClick={()=>go("player",{player:p.id})}>Profile</button><button className="btn ghost" onClick={()=>go("report",{player:p.id})}>Report</button></div></div>)}</Card></div>;}
function Notes({go,saved,setSaved}){const [d,setD]=useState("Observation: "); return <div className="stack lg"><Card title="Study Notes" right={<button className="btn" onClick={()=>go("answer",{qid:"notes-followup"})}>Add from AI</button>}><div className="grid two"><div className="panel inset"><div className="panelTitle">Saved notes</div>{saved.map((n,i)=><div key={i} className="noteCard">{n}</div>)}</div><div className="panel inset"><div className="panelTitle">New note</div><textarea className="textarea" value={d} onChange={e=>setD(e.target.value)}/><div className="rowActions mt"><button className="btn primary" onClick={()=>{if(d.trim()) setSaved([d.trim(),...saved]); setD("Observation: ");}}>Save</button><button className="btn" onClick={()=>go("report",{player:"p1"})}>Send to Report</button></div></div></div></Card></div>;}
function Pricing(){return <div className="stack lg"><Card title="Pricing / Gating (MVP test)" right={<span className="pill">Validation-ready</span>}><div className="grid two"><div className="priceCard"><div className="rowTitle">Free</div><div className="price">$0</div><ul><li>Limited tournament views</li><li>Limited AI questions/day</li><li>Basic highlights access</li><li>No full exploit report export</li></ul></div><div className="priceCard featured"><div className="rowTitle">HUDR Pro</div><div className="price">$10<span>/mo</span></div><ul><li>Full exploit reports</li><li>AI tournament/player/hand/strategy tabs</li><li>Evidence-linked insights + hand jumps</li><li>Replay-linked study workflow</li><li>Watchlist + notes</li></ul><button className="btn primary full">Start Pro (UI)</button></div></div></Card></div>;}
function Settings(){return <div className="stack lg"><Card title="Settings / Prototype Notes"><div className="grid two"><div className="stack"><div className="metric"><span>Prototype goal</span><strong>MVP release flow with all links working</strong></div><div className="metric"><span>Routing</span><strong>Hash-based (static friendly)</strong></div><div className="metric"><span>Focus</span><strong>Tournament → AI → Evidence → Replay → Report</strong></div></div><div className="stack"><div className="metric"><span>Next step</span><strong>react-router + API integration</strong></div><div className="metric"><span>Replace mocks</span><strong>HUDR endpoints + auth + analytics</strong></div><div className="metric"><span>Release mode</span><strong>Paid beta validation</strong></div></div></div></Card></div>;}
